# fly.toml file generated for dean on 2022-11-01T12:24:10+08:00

app = "dean"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "build/Dockerfile"

[env]
  PORT = "5000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = "5000"

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"